### ISSUE TITLE
ebiten.Run() is deprecated on Ebiten v1.12

### ISSUE THREAD

**Issue by Myu-Unix** [Myu-Unix/mirkwood_engine#1]
https://pkg.go.dev/github.com/hajimehoshi/ebiten#Run

**Comment by Myu-Unix** [comment]
Fixed with https://github.com/Myu-Unix/mirkwood_engine/commit/d4375237e3fdb6f3f819008881c3280e446d830c

**Comment by hajimehoshi** [comment]
Hi, if you want to use the latest Ebiten (v2), I strongly recommend to use Go modules (i.e., put go.mod file). Now apparently this project disables Go modules in the Makefile.

**Comment by Myu-Unix** [comment]
Hello Hajime ! Yes I would like to investigate ebiten v2, right now, my code is working on my computer but not when built elsewhere

I realized I was using a version of ebiten before < 1.12 , I am trying to bring the code to proper 1.12 then v2 will be next but I must admit I am struggling a bit

I'll definitely investigate go modules, I didn't knew about them

**Comment by hajimehoshi** [comment]
Thanks! The simplest way is

* Update Go to 1.16 if needed
* Run `go mod init github.com/Myu-Unix/mirkwood_engine` to create go.mod.
* Remove `GO111MODULE=off` from `build.sh`
* Add `go mod tidy` to `build.sh` before `go build`
* Replace all the import paths `github.com/hajimehoshi/ebiten` with `github.com/hajimehoshi/ebiten/v2` (`github.com/hajimehoshi/ebiten/ebitenutuil` will be `github.com/hajimehoshi/ebiten/v2/ebitenutil`, and so on)

That should be all.

https://golang.org/doc/modules/managing-dependencies is a good resource to learn Go modules.

**Comment by Myu-Unix** [comment]
Wow, thank you so much for the clear explanations ! I have moved to `go mod`, Ebiten v2 and tested the compile on another computer and all is well apparently :) `go mod` is such a useful way to handle deps, it was kind of a black box to me before.

**Comment by hajimehoshi** [comment]
I'm glad to hear that!

* Strictly speaking, `go mod tidy` is needed only when you change or update the dependencies. I'm sorry for confusing, but removing `go mod tidy` from build.sh would be better.
* `go.sum` should be in the repository for other people to get correct dependencies.

Thanks!
